### ISSUE TITLE
Is `trunk check` open source

### ISSUE THREAD

**Issue by kevcube** [trunk-io/trunk-action#8]
Hi, started using trunk yesterday and I dig it, but I'm wondering if the tool itself is open source?

Running on M1 Mac and it's taking a bit of CPU because it's not compiled for darwin-arm64, was hoping to open an issue on the main repository but not seeing that repo.

**Comment by kevcube** [comment]
Found there's an arm64 package on brew.sh, installed, but when I set `"trunk.trunkPath": "/opt/homebrew/bin/trunk"` in VSCode I get an error.

**Comment by det** [comment]
Hi Kevin!

Thanks for letting us know this is important to you. While trunk is not open-source, we do have arm64 support on the roadmap, and hearing feedback like this helps us prioritize. FWIW, my personal experience with rosetta and particularly trunk + rosetta has been very positive without any notice of slowness.
